### ISSUE TITLE
Docs reference outdated GitHub Action

### ISSUE THREAD

**Issue by jmreicha** [puzzle/goff#73]
The example in the docs for the GitHub integration references a GitHub Acction to an archived repository (machine-learning-apps/pr-comment) that appears to be in a broken state as is https://github.com/puzzle/goff/blob/main/docs/integrations.md.

I haven't had a chance to dig into a replacement yet, just thought I would let folks know.

**Comment by jmreicha** [comment]
This appears to work as a replacement.

```yaml
- name: PR comment with file
  uses: thollander/actions-comment-pull-request@v2
  with:
    filePath: diff.md
```

I can open a PR to update docs if you'd like.
